// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.9
// source: pkg/gopher/gopher.proto

package go_gopher_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Str      string  `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	Number   int64   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Floating float64 `protobuf:"fixed64,3,opt,name=floating,proto3" json:"floating,omitempty"`
}

func (x *Object) Reset() {
	*x = Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gopher_gopher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gopher_gopher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_pkg_gopher_gopher_proto_rawDescGZIP(), []int{0}
}

func (x *Object) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

func (x *Object) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Object) GetFloating() float64 {
	if x != nil {
		return x.Floating
	}
	return 0
}

// The request message containing the user's name.
type GopherRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data1  string  `protobuf:"bytes,2,opt,name=data1,proto3" json:"data1,omitempty"`
	Data2  int64   `protobuf:"varint,3,opt,name=data2,proto3" json:"data2,omitempty"`
	Data3  float64 `protobuf:"fixed64,4,opt,name=data3,proto3" json:"data3,omitempty"`
	Object *Object `protobuf:"bytes,5,opt,name=object,proto3" json:"object,omitempty"`
}

func (x *GopherRequest) Reset() {
	*x = GopherRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gopher_gopher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GopherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GopherRequest) ProtoMessage() {}

func (x *GopherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gopher_gopher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GopherRequest.ProtoReflect.Descriptor instead.
func (*GopherRequest) Descriptor() ([]byte, []int) {
	return file_pkg_gopher_gopher_proto_rawDescGZIP(), []int{1}
}

func (x *GopherRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GopherRequest) GetData1() string {
	if x != nil {
		return x.Data1
	}
	return ""
}

func (x *GopherRequest) GetData2() int64 {
	if x != nil {
		return x.Data2
	}
	return 0
}

func (x *GopherRequest) GetData3() float64 {
	if x != nil {
		return x.Data3
	}
	return 0
}

func (x *GopherRequest) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

// The response message containing the greetings
type GopherReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GopherReply) Reset() {
	*x = GopherReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gopher_gopher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GopherReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GopherReply) ProtoMessage() {}

func (x *GopherReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gopher_gopher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GopherReply.ProtoReflect.Descriptor instead.
func (*GopherReply) Descriptor() ([]byte, []int) {
	return file_pkg_gopher_gopher_proto_rawDescGZIP(), []int{2}
}

func (x *GopherReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_gopher_gopher_proto protoreflect.FileDescriptor

var file_pkg_gopher_gopher_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x70,
	0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x67, 0x6f, 0x70, 0x68, 0x65,
	0x72, 0x22, 0x4e, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x74, 0x72, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x22, 0x8d, 0x01, 0x0a, 0x0d, 0x47, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x31,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x31, 0x12, 0x14, 0x0a,
	0x05, 0x64, 0x61, 0x74, 0x61, 0x32, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x64, 0x61,
	0x74, 0x61, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x33, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x33, 0x12, 0x26, 0x0a, 0x06, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x70, 0x68,
	0x65, 0x72, 0x2e, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x22, 0x27, 0x0a, 0x0b, 0x47, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x45, 0x0a, 0x06, 0x47, 0x6f,
	0x70, 0x68, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x47, 0x6f, 0x70, 0x68, 0x65,
	0x72, 0x12, 0x15, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x2e, 0x47, 0x6f, 0x70, 0x68, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x65,
	0x72, 0x2e, 0x47, 0x6f, 0x70, 0x68, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x00, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x63, 0x72, 0x61, 0x6c, 0x79, 0x2f, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2d,
	0x62, 0x79, 0x2d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x2d, 0x67,
	0x6f, 0x70, 0x68, 0x65, 0x72, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_gopher_gopher_proto_rawDescOnce sync.Once
	file_pkg_gopher_gopher_proto_rawDescData = file_pkg_gopher_gopher_proto_rawDesc
)

func file_pkg_gopher_gopher_proto_rawDescGZIP() []byte {
	file_pkg_gopher_gopher_proto_rawDescOnce.Do(func() {
		file_pkg_gopher_gopher_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_gopher_gopher_proto_rawDescData)
	})
	return file_pkg_gopher_gopher_proto_rawDescData
}

var file_pkg_gopher_gopher_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_gopher_gopher_proto_goTypes = []interface{}{
	(*Object)(nil),        // 0: gopher.object
	(*GopherRequest)(nil), // 1: gopher.GopherRequest
	(*GopherReply)(nil),   // 2: gopher.GopherReply
}
var file_pkg_gopher_gopher_proto_depIdxs = []int32{
	0, // 0: gopher.GopherRequest.object:type_name -> gopher.object
	1, // 1: gopher.Gopher.GetGopher:input_type -> gopher.GopherRequest
	1, // 2: gopher.Gopher.GetGopher:output_type -> gopher.GopherRequest
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_gopher_gopher_proto_init() }
func file_pkg_gopher_gopher_proto_init() {
	if File_pkg_gopher_gopher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_gopher_gopher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gopher_gopher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GopherRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gopher_gopher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GopherReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_gopher_gopher_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_gopher_gopher_proto_goTypes,
		DependencyIndexes: file_pkg_gopher_gopher_proto_depIdxs,
		MessageInfos:      file_pkg_gopher_gopher_proto_msgTypes,
	}.Build()
	File_pkg_gopher_gopher_proto = out.File
	file_pkg_gopher_gopher_proto_rawDesc = nil
	file_pkg_gopher_gopher_proto_goTypes = nil
	file_pkg_gopher_gopher_proto_depIdxs = nil
}
